spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${USER_NAME}
    password: ${PASSWORD_RABBITMQ}
    listener:
      simple:
        retry:
          enable: true
          max-attempts: 4
          initial-interval: 5000
          multiplier: 2
          max-interval: 300000